INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (1, 'WTI Crude', 1);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (2, 'Brent Crude', 1);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (3, 'Mars US', 1);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (4, 'Opec Basket', 1);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (5, 'Canadian Crude Index', 1);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (6, 'DME Oman', 1);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (7, 'Urals', 1);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (8, 'Mexican Basket', 1);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (9, 'Indian Basket', 1);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (10, 'Western Canadian Select', 1);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (11, 'Dubai', 1);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (12, 'Brent Weighted Average', 1);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (13, 'Louisiana Light', 1);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (14, 'Coastal Grade A', 1);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (15, 'Domestic Swt. @ Cushing', 1);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (16, 'Giddings', 1);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (17, 'ANS West Coast', 1);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (18, 'Gulf Coast HSFO', 1);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (19, 'Natural Gas', 1);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (20, 'Heating Oil', 1);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (21, 'Gasoline', 1);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (22, 'Ethanol', 1);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (23, 'Marine', 2);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (24, 'Murban', 2);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (25, 'Iran Heavy', 2);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (26, 'Basra Light', 2);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (27, 'Saharan Blend', 2);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (28, 'Bonny Light', 2);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (29, 'Girassol', 2);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (30, 'Arab Light', 2);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (31, 'Zafiro', 2);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (32, 'Das', 3);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (33, 'Qatar Land - Qatar', 3);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (34, 'Al Shaheen - Qatar', 3);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (35, 'Basrah Heavy', 3);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (36, 'Arab Extra Light', 3);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (37, 'Arab Heavy', 3);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (38, 'Brass River', 3);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (39, 'Qua Iboe', 3);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (40, 'Cabinda', 3);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (41, 'Nemba', 3);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (42, 'Dalia', 3);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (43, 'Cossack', 3);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (44, 'Maya', 3);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (45, 'Isthmus', 3);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (46, 'Olmeca', 3);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (47, 'Iran Light', 3);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (48, 'Forozan Blend', 3);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (49, 'Soroosh', 3);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (50, 'Daqing', 3);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (51, 'Shengli', 3);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (52, 'South China Sea', 3);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (53, 'Cinta', 3);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (54, 'Duri', 3);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (55, 'Minas', 3);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (56, 'ESPO', 3);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (57, 'Sokol', 3);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (58, 'Tapis (Malaysia)', 3);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (59, 'Central Alberta', 4);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (60, 'Light Sour Blend', 4);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (61, 'Peace Sour', 4);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (62, 'Syncrude Sweet Premium', 4);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (63, 'Sweet Crude', 4);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (64, 'US High Sweet Clearbrook', 4);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (65, 'Canadian Condensate', 4);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (66, 'Midale', 4);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (67, 'Albian Heavy Synthetic', 4);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (68, 'Hardisty Light', 4);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (69, 'Premium Synthetic', 4);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (70, 'West Texas Sour', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (71, 'West Texas Intermediate', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (72, 'Upper Texas Gulf Coast', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (73, 'Texas Gulf Coast Light', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (74, 'South Texas Sour', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (75, 'North Texas Sweet', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (76, 'North Texas Sour', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (77, 'Eagle Ford Pipeline', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (78, 'Eagle Ford Condensate', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (79, 'Eagle Ford', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (80, 'Tx. Upper Gulf Coast', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (81, 'South Texas Light', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (82, 'W. Tx./N. Mex. Inter.', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (83, 'South Texas Heavy', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (84, 'W. Cen. Tx. Inter.', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (85, 'East Texas Sweet', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (86, 'Arkansas Sweet', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (87, 'Arkansas Sour', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (88, 'Arkansas Ex Heavy', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (89, 'Buena Vista', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (90, 'Midway-Sunset', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (91, 'Williston Sweet', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (92, 'Williston Sour', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (93, 'Utah Black Wax', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (94, 'Four Corners', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (95, 'Colorado D-J Basin', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (96, 'Colorado South East', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (97, 'Colorado West', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (98, 'Kansas Common', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (99, 'Eastern Kansas', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (100, 'NW Kansas Sweet', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (101, 'SW Kansas Sweet', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (102, 'South Central Kansas', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (103, 'Delhi/N. Louisiana', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (104, 'South Louisiana', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (105, 'North Louisiana Sweet', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (106, 'Michigan Sour', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (107, 'Michigan Sweet', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (108, 'Nebraska Sweet', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (109, 'Oklahoma Sweet', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (110, 'Oklahoma Sour', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (111, 'Western Oklahoma Swt.', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (112, 'Oklahoma Intermediate', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (113, 'Wyoming General Sour', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (114, 'Wyoming General Sweet', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (115, 'Central Montana', 5);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (116, 'Basrah Light', 6);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (117, 'Es Sider', 6);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (118, 'Kuwait Export', 6);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (119, 'Merey', 6);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (120, 'Oriente', 6);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (121, 'Indonesia Crude Price', 6);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (122, '78.53', null);
INSERT INTO test.oil_price_indices (index_id, index_name, category_id) VALUES (123, 'Kuwait Export Blend', null);
